/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package bz.davide.dmwebexamples.shared.component;


public class Example01Marshaller_Helper extends bz.davide.dmwebexamples.shared.Example01Marshaller_Helper
{
   protected Example01Marshaller_Helper()
   {
      this.putClassMarshaller("bz.davide.dmwebexamples.shared.component.Calculator", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            internalMarschall(obj, "bz.davide.dmweb.shared.view.DivView", "N/A",structure, identities, seq, true);
            Object value;
            // inputView
            value = ((bz.davide.dmwebexamples.shared.component.Calculator)obj).inputView;
            if (value == null)
               structure.property("inputView").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.InputView", structure.property("inputView").structure(), identities, seq, false);
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmwebexamples.shared.component.NumberButtonClick", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // calculator
            value = ((bz.davide.dmwebexamples.shared.component.NumberButtonClick)obj).calculator;
            if (value == null)
               structure.property("calculator").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmwebexamples.shared.component.Calculator", structure.property("calculator").structure(), identities, seq, false);
            }
            // num
            value = ((bz.davide.dmwebexamples.shared.component.NumberButtonClick)obj).num;
            if (value == null)
               structure.property("num").nullValue();
            else
            {
                    structure.property("num").integer((Integer)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmwebexamples.shared.component.PhotoGallery", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            internalMarschall(obj, "bz.davide.dmweb.shared.view.DivView", "N/A",structure, identities, seq, true);
            Object value;
            // currIndex
            value = ((bz.davide.dmwebexamples.shared.component.PhotoGallery)obj).currIndex;
            if (value == null)
               structure.property("currIndex").nullValue();
            else
            {
                    structure.property("currIndex").integer((Integer)value);                          
            }
            // imageBoxes
            value = ((bz.davide.dmwebexamples.shared.component.PhotoGallery)obj).imageBoxes;
            if (value == null)
               structure.property("imageBoxes").nullValue();
            else
            {
               java.util.ArrayList arrayList = (java.util.ArrayList)value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("imageBoxes").array();        
               for (Object o: arrayList) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                  else                                                        
                     internalMarschall(o, o.getClass().getName(), "bz.davide.dmweb.shared.view.DivView", array.item().structure(), identities, seq, false);
               }                                                              
            }
            // lastIndex
            value = ((bz.davide.dmwebexamples.shared.component.PhotoGallery)obj).lastIndex;
            if (value == null)
               structure.property("lastIndex").nullValue();
            else
            {
                    structure.property("lastIndex").integer((Integer)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmwebexamples.shared.component.PhotoGalleryAttachListener", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // gallery
            value = ((bz.davide.dmwebexamples.shared.component.PhotoGalleryAttachListener)obj).gallery;
            if (value == null)
               structure.property("gallery").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmwebexamples.shared.component.PhotoGallery", structure.property("gallery").structure(), identities, seq, false);
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmwebexamples.shared.component.Notepad", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            internalMarschall(obj, "bz.davide.dmweb.shared.view.DivView", "N/A",structure, identities, seq, true);
            Object value;
            // localStorageKeyName
            value = ((bz.davide.dmwebexamples.shared.component.Notepad)obj).localStorageKeyName;
            if (value == null)
               structure.property("localStorageKeyName").nullValue();
            else
            {
                    structure.property("localStorageKeyName").string((String)value);                          
            }
            // textArea
            value = ((bz.davide.dmwebexamples.shared.component.Notepad)obj).textArea;
            if (value == null)
               structure.property("textArea").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.TextAreaView", structure.property("textArea").structure(), identities, seq, false);
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmwebexamples.shared.component.NotepadSave", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // notepad
            value = ((bz.davide.dmwebexamples.shared.component.NotepadSave)obj).notepad;
            if (value == null)
               structure.property("notepad").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmwebexamples.shared.component.Notepad", structure.property("notepad").structure(), identities, seq, false);
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("bz.davide.dmwebexamples.shared.component.NotepadAttach", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // notepad
            value = ((bz.davide.dmwebexamples.shared.component.NotepadAttach)obj).notepad;
            if (value == null)
               structure.property("notepad").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmwebexamples.shared.component.Notepad", structure.property("notepad").structure(), identities, seq, false);
            }
            if (!superClass)
               structure.close();
         }
      });

   }
}
