/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package bz.davide.dmwebexamples.shared;


public class Example01Unmarshaller_Helper extends bz.davide.dmweb.shared.view.Example01Unmarshaller_Helper
{
   protected Example01Unmarshaller_Helper()
   {
      this.putInstanceFactory("bz.davide.dmwebexamples.shared.Example01AttachListener", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new bz.davide.dmwebexamples.shared.Example01AttachListener((Void)null);
         }
      });

      this.putClassUnmarshaller("bz.davide.dmwebexamples.shared.Example01AttachListener", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // example01
            if ((value = structure.property("example01")) != null)
               if (value.isNull())
                  ((Example01AttachListener)obj).example01 = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((Example01AttachListener)obj).example01 = (bz.davide.dmwebexamples.shared.Example01)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("Example01"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((Example01AttachListener)obj).example01 = (bz.davide.dmwebexamples.shared.Example01)o;
                  }
               }
         }
      });
      this.putInstanceFactory("bz.davide.dmwebexamples.shared.ButtonClickListener", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new bz.davide.dmwebexamples.shared.ButtonClickListener((Void)null);
         }
      });

      this.putClassUnmarshaller("bz.davide.dmwebexamples.shared.ButtonClickListener", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // example01
            if ((value = structure.property("example01")) != null)
               if (value.isNull())
                  ((ButtonClickListener)obj).example01 = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((ButtonClickListener)obj).example01 = (bz.davide.dmwebexamples.shared.Example01)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("Example01"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((ButtonClickListener)obj).example01 = (bz.davide.dmwebexamples.shared.Example01)o;
                  }
               }
         }
      });
      this.putInstanceFactory("bz.davide.dmwebexamples.shared.Example01", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new bz.davide.dmwebexamples.shared.Example01((Void)null);
         }
      });

      this.putClassUnmarshaller("bz.davide.dmwebexamples.shared.Example01", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            internalUnmarschall(structure, "bz.davide.dmweb.shared.view.DivView", obj, identities);
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
         }
      });

   }
}
